name = "reddit_clone"
version = "1.0.0"

[dependencies]
gleam_stdlib = "0.36.0"
gleam_erlang = "0.26.0"
gleam_otp = "0.10.0"
gleam_http = "3.6.0"
gleam_json = "1.0.0"
gleam_httpc = "2.2.0"
argv = "1.0.2"
mist = "1.2.0"

[dev-dependencies]
gleeunit = "1.0.0"

